services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\CoreBundle\:
        resource: '../../*'

    whatwedo\CoreBundle\EventListener\JsonRequestTransformerListener:
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 100 }
