services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    whatwedo\CoreBundle\:
        resource: '../../*'

    whatwedo\CoreBundle\Manager\FormatterManager:
        arguments:
            - !tagged_iterator 'whatwedo_core.formatter'
