services:
    whatwedo_core.event_listener.json_request_transformer:
        class: whatwedo\CoreBundle\EventListener\JsonRequestTransformerListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }
