services:
    whatwedo_core.manager.formatter:
        class: whatwedo\CoreBundle\Manager\FormatterManager

    whatwedo\CoreBundle\Manager\FormatterManager: '@whatwedo_core.manager.formatter'

    whatwedo\CoreBundle\Formatter\:
        resource: '../../Formatter/*'
        exclude: '../../Formatter/{AbstractFormatter.php,AbstractSimpleEnumFormatter.php}'
        tags:
          - core.formatter

    whatwedo_core.event_listener.json_request_transformer:
        class: whatwedo\CoreBundle\EventListener\JsonRequestTransformerListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, priority: 100 }
