services:
    _defaults:
        autowire: true
        autoconfigure: true

    # Event Listeners
    whatwedo_core.event_listener.json_request_transformer:
        class: whatwedo\CoreBundle\EventListener\JsonRequestTransformerListener
        tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 100 }

    # Manager
    whatwedo_core.manager.formatter:
        class: whatwedo\CoreBundle\Manager\FormatterManager
        public: true

    # Formatter
    whatwedo\CoreBundle\Formatter\:
        resource: '../../Formatter/*'
        exclude: '../../Formatter/{AbstractFormatter.php,AbstractSimpleEnumFormatter.php}'
        tags:
          - core.formatter
