services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    araise\CoreBundle\:
        resource: '../../*'

    araise\CoreBundle\Twig\CoreTurboExtension:
        arguments: ["%araise_core.enable_turbo%"]
